### PR TITLE
Merging test time!

### PR DESCRIPTION
**Pull request by jasonkuster**

### CODE REVIEW

**Comment by jasonkuster** [comment]
@beam-testing merge

**Comment by beam-testing** [comment]
Info: Adding PR to work queue; current position: 1.

**Comment by beam-testing** [comment]
Info: MergeBot starting work on PR#5.

**Comment by beam-testing** [comment]
Error: Automatic rebase failed. Please rebase branch against apache/master and try again.

**Comment by jasonkuster** [comment]
@beam-testing merge

**Comment by beam-testing** [comment]
Info: Adding PR to work queue; current position: 1.

**Comment by beam-testing** [comment]
Info: MergeBot starting work on PR#5.

**Comment by beam-testing** [comment]
Info: Job verification started. Verification job is [here](https://35.184.226.36:8080/job/mb-merge-1/2) (may still be pending; if page 404s, check job status page [here](https://35.184.226.36:8080/job/mb-merge-1/)).

**Comment by beam-testing** [comment]
Info: PR merge succeeded!

**Pull request merged**
